### ISSUE TITLE
Pinning to Pinata does not work

### ISSUE THREAD

**Issue by psiemens** [packagelabs/freshmint#75]
Pinning to Pinata fails with the following error when using both the Pinning Services API and Pinata's Pinning API:

```
Error
    at Function.storeBlob (/Users/petersiemens/dev/freshmint/node_modules/nft.storage/dist/src/lib.cjs:111:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async IPFS.pin (/Users/petersiemens/dev/freshmint/dist/cli/ipfs.js:9:16)
    at async MetadataProcessor.processIpfsFile (/Users/petersiemens/dev/freshmint/dist/cli/metadata/MetadataProcessor.js:60:21)
    at async MetadataProcessor.process (/Users/petersiemens/dev/freshmint/dist/cli/metadata/MetadataProcessor.js:39:34)
    at async /Users/petersiemens/dev/freshmint/dist/cli/minters/StandardMinter.js:82:23
    at async Promise.all (index 3)
    at async StandardMinter.processTokenBatch (/Users/petersiemens/dev/freshmint/dist/cli/minters/StandardMinter.js:80:16)
    at async StandardMinter.mint (/Users/petersiemens/dev/freshmint/dist/cli/minters/StandardMinter.js:38:36)
    at async Fresh.mintNFTsFromCSVFile (/Users/petersiemens/dev/freshmint/dist/cli/fresh.js:25:9)
```

**Comment by psiemens** [comment]
In order to provide better batch uploading / pinning, the current Freshmint CLI uses the NFT.Storage HTTP API rather than the generic IPFS Pinning Services API.

I need to investigate and see if it is possible to get the same batch pinning support from the Pinning Services API. If so, it might be possible to integrate both NFT.Storage and Pinata with the same code. But if not, it may be better to integrate Pinata's API directly to achieve feature parity with NFT.Storage.

Closing for now in favour of other priorities, but may reopen at a later date.
